### PR TITLE
Add deployment.spec.replicas and ingress.metadata.name

### PR DESCRIPTION
**Pull request by bismarkanes**
- A Deployment is now the recommended way to set up replication:

https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/

image

- Add Ingress default name

### CODE REVIEW

**Comment by TxGVNN** [comment]
Thank you very much. I'm reviewing a bit. Could you check on my comment?

**Comment by bismarkanes** [comment]
Yes thank you for the comment, let me know if there any advise or it's ok too to close

**Comment by TxGVNN** [comment]
> Yes thank you for the comment, let me know if there any advise or it's ok too to close

Thanks for your contributing. I push my comment (Github call a review) at https://github.com/TxGVNN/emacs-k8s-mode/pull/10/files/4a32cb44f1aab6affc0baf515a6b527777220b1d

About the replicas should be 1 by default instead n

**Comment by bismarkanes** [comment]
Yes you are right, it's better to have 1 as default. I have push the commit. Let me know if you prefer me to recompile into 1 commit. Thank you.

**Comment by TxGVNN** [comment]
Thank you. Merged!

**Pull request merged**
